[project]
name = "peto"
version = "0.1.0"
description = "Command line reptile enclosure"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "psutil>=6.1.0",
    "requests>=2.32.3",
    "termcolor",
]
