
# pets/pet_base.py
INITIAL_HEALTH = 100
INITIAL_AGE = 0
INITIAL_MOOD = 50
INITIAL_HUNGER = 50

# pets/frog.py
PREFERRED_FOOD_FROG = ['.jpg', '.jpeg', '.png']
INITIAL_JUMP_HEIGHT = 10

# pets/turtle.py
PREFERRED_FOOD_TURTLE = ['.txt', '.docx', '.pdf']
INITIAL_SHELL_STRENGTH = 10

# pets/actions/eating.py
NUTRITIONAL_VALUE_THRESHOLD = 1.5
HAMMING_DISTANCE_THRESHOLD = 10
FOOD_DIVIDER_FROG = 100_000
FOOD_DIVIDER_TURTLE = 1_000

# pets/actions/playing.py
MOOD_INCREASE_DIVIDER = 100
CODE_404_DECREASE = -8
CODE_403_DECREASE = -5
CODE_500_DECREASE = -10
CODE_OTHER_DECREASE = -2
DEFAULT_DECREASE = -3
