
# pets/pet_base.py
INITIAL_HEALTH = 100.0
INITIAL_AGE = 0.0
INITIAL_MOOD = 50.0
INITIAL_HUNGER = 50.0
HUNGER_GAIN_RATE = 0.001
MOOD_LOSS_RATE = 0.001
HEALTH_LOSS_RATE = 0.001
AGE_GAIN_RATE = 0.05


# pets/frog.py
PREFERRED_FOOD_FROG = ['.jpg', '.jpeg', '.png']
INITIAL_JUMP_HEIGHT = 10

# pets/turtle.py
PREFERRED_FOOD_TURTLE = ['.txt', '.docx', '.pdf']
INITIAL_SHELL_STRENGTH = 10

# pets/crocodile.py
PREFERRED_FOOD_CROCODILE = ['.exe', '.py', '.sh']
INITIAL_BITE_FORCE = 20

# pets/actions/eating.py
NUTRITIONAL_VALUE_THRESHOLD = 1.5
HAMMING_DISTANCE_THRESHOLD = 10
FOOD_DIVIDER_FROG = 100_000
FOOD_DIVIDER_TURTLE = 1_000
FOOD_DIVIDER_CROCODILE = 100_000

# pets/actions/playing.py
MOOD_INCREASE_DIVIDER = 100
CODE_404_DECREASE = -8
CODE_403_DECREASE = -5
CODE_500_DECREASE = -10
CODE_OTHER_DECREASE = -2
DEFAULT_DECREASE = -3

# services/penc.py
PENC_FILE_EXTENSION = ".penc"
